---
- name: Install ZSH
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present
- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh'
    depth: 1
    version: master
- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: '{{ ansible_env.HOME }}/.config/zsh/plugins/zsh-autosuggestions'
    depth: 1
    version: master
- name: Install zsh-completions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: '{{ ansible_env.HOME }}/.config/zsh/plugins/zsh-completions'
    depth: 1
    version: master
- name: Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: '{{ ansible_env.HOME }}/.config/zsh/plugins/zsh-syntax-highlighting'
    depth: 1
    version: master
- name: Install catppuccin theme for syntax highlighting
  ansible.builtin.git:
    repo: https://github.com/catppuccin/zsh-syntax-highlighting.git
    dest: '{{ ansible_env.HOME }}/src/zsh-syntax-highlighting'
    depth: 1
    version: main
- name: Move highlighting theme in the right location
  ansible.builtin.command:
    cmd: cp catppuccin_mocha-zsh-syntax-highlighting.zsh {{ ansible_env.HOME }}/.config/zsh/
    chdir: '{{ ansible_env.HOME }}/src/zsh-syntax-highlighting/themes'
    creates: '{{ ansible_env.HOME }}/.config/zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh'
- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    shell: /bin/zsh
