- name: Install ZSH
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1
 
- name: Install zsh-autosuggestions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    depth: 1

 
- name: Install zsh-completions plugin # noqa: latest

  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1
 
- name: Install zsh-syntax-highlighting plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git

    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1
 
- name: Install catppuccin theme for syntax highlighting
  ansible.builtin.git:
    repo: https://github.com/catppuccin/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/src/zsh-syntax-highlighting"
    depth: 1

- name: Move highlighting theme in the right location
  ansible.builtin.shell:
    cmd: cp catppuccin_mocha-zsh-syntax-highlighting.zsh ~/.zsh/
    chdir: "{{ ansible_env.HOME }}/src/zsh-syntax-highlighting/themes"

- name: Move custom prompt file managed in dotfiles to custom theme location
  ansible.builtin.shell:
    cmd: cp "{{ ansible_env.HOME }}/.zsh/catppuccin.zsh-theme" "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/"
    chdir: "{{ ansible_env.HOME }}"

- name: Change user shell to zsh 
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

