---
- name: Bootstrap dev environment
  hosts: localhost
  tasks:
    - name: Install packages with apt
      become: true
      ansible.builtin.apt:
        name: [software-properties-common, git, bat, fzf, ripgrep, stow]
        state: latest
  roles: [nvim, tmux, shell, zoxide, tldr]
