---
- name: Bootstrap dev environment
  hosts: localhost
  tasks:
    - name: Install packages with apt
      become: true
      ansible.builtin.apt:
        update-cache: true
        name:
          - software-properties-common
          - git
          - bat
          - fzf
          - python3-debian
          - ripgrep
          - stow
        state: latest
  roles: [nvim, tmux, shell, terraform, zoxide, tldr]
