---
- name: Add terraform ppa repo
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: [deb]
    uris: https://apt.releases.hashicorp.com
    components: main
    suites: '{{ ansible_distribution_release }}'
    signed_by: https://apt.releases.hashicorp.com/gpg
    state: present
    enabled: true
  become: true
- name: Install terraform
  ansible.builtin.apt:
    update-cache: true
    name: [terraform]
    state: present
  become: true
